### ISSUE TITLE
RE: Addition of different lenses and mirrors?

### ISSUE THREAD

**Issue by jdlake** [CodeFHD/OptiCore#1]
This is a really great tool. Thank you for open sourcing it. I just wonder if you have plans to add off-axis parabolic surfaces, parabolic surfaces and other types of lenses i.e. aspheric?

Many thanks

Jamie

**Comment by CodeFHD** [comment]
Hi Jamie,

thanks for your interest in the module! (May I ask how you found it?)

Yes, I have plans to add more features. I just pushed an updated readme with a "todo"-list I already wrote, where I collected a list of optical elements that could be modelled. You can have a look at that.

Off-axis parabolic mirrors are already implemented. I also already started implementing aspheric surfaces (standard formula with three even coefficients for now).

At the moment my only priotrity is D-shaped lenses and a check for some artifacts. The rest is pretty much for fun, so if you have a need for a specific geometry, let me know here.

Cheers

**Comment by jdlake** [comment]
Code, 

I came to know about this via the LuxRender forum. I came to know about LuxRender because of its BiPT capabilities. I'm designing my laser setup in Blender for publication in scientific papers and these lenses are a real time-saver!

The todo list you have written is great. The specific OAP mirrors I use have a hole in their center. 

Also, have you any idea how to model beamsplitters with Lux?

Thank you

**Comment by CodeFHD** [comment]
That sounds like a great application! And you know about the forum already, too...

Mirrors with holes should be doable.

For a beamsplitter, you could start with a cylinder or square box. Set up a glass material with volumes as you would for a lens. Then assign a second material where you mix glass with mirror-material and assign that to one of the surfaces. I didn't test this, but that would be my first guess.

**Comment by jdlake** [comment]
Code, the beamsplitter works quite nicely, actually. Much better than expected. Thanks! I will add a picture of the optical pump laser setup once it's done!

**Comment by CodeFHD** [comment]
Ok great! You should then upload it to the LuxCore forum :)

I've already started working on the mirror with central hole. I will announce it also on the forum when I have a new version ready.

**Comment by CodeFHD** [comment]
FYI, I just pushed an update. Lenses now have an aspheric option, and mirrors a central hole option.

I only included holes along the collimated beam direction for now, along the focus would be far more difficult to implement. If you need that, i suggest for now you try to do t with a boolean operation.

Aspheric surfaces on lenses might still be somehwat limited because of sanity checks for the pure spherical shape. This requires future updates.

**Comment by justinclift** [comment]
> I will add a picture of the optical pump laser setup once it's done!

@jdlake Any update? (Just out of curiosity really) :wink:
