### ISSUE TITLE
add on err

### ISSUE THREAD

**Issue by waynech7** [CodeFHD/OptiCore#11]
hi I addon opticore elements but I get the following error 
""Traceback (most recent call last):
  File "D:\BBlender\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\wayne\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\OptiCore-master\__init__.py", line 18, in <module>
    from .elements import OBJECT_OT_add_lens, OBJECT_OT_add_sqlens, OBJECT_OT_add_mirror, OBJECT_OT_add_CCretro, OBJECT_OT_add_siemens
ImportError: cannot import name 'OBJECT_OT_add_lens' from 'OptiCore-master.elements' (unknown location)""

**Comment by CodeFHD** [comment]
I was able to reproduce the error by renaming/removing the file __init__.py inside the elements/ subdirectory.

Hence, I suggest you re-install the addon to fix the files and their locations.
