### ISSUE TITLE
Can we add ray visualizations to the viewport ?

### ISSUE THREAD

**Issue by melihozaydin** [CodeFHD/OptiCore#18]
Title says it all. I am a blender noob but realtime feedback of how rays behave in the viewport would help to develop and adjust stuff faster. 
I have found something that might work at this link: https://blender.stackexchange.com/questions/150277/how-to-visualize-reflection-of-a-beam-or-ray

What do you think ?

**Comment by CodeFHD** [comment]
Could you elaborate a little more on what exactly you are looking for?

OptiCore already has ray visualisation for lenses. See the "Add Ray Fan" option in the screenshot below.
Of course, these ray fans are limited to a single lens currently generated at one time.

The method in the link you suggested could be used to extend rays into a scene behind it, however it could (probably) not include refracttion at other lenses that were created before. This might be useful for illumination applications, but I am not sure if that is your interest.

![grafik](https://github.com/CodeFHD/OptiCore/assets/48182552/c91dae11-8c73-408b-97c8-5172e772966d)

**Comment by melihozaydin** [comment]
I have not had much time with the addon so i did not know about the "add ray fan" option.

I want to be able to design multi-element lenses and play around with their parameters in real time to achieve a certain ray behaviour.

But from what you said, ray visualization only being limited for single lenses makes it insufficient. 

If i could place something like a light source in the scene that casts a visual ray fan that i can trace through the optical setup that would probably serve this purpose.

As a side note: 
I also couldnt find a way to edit lens properties after adding it. it might be related to this: 
[How to edit Parameters for an Object after it is created?](https://blender.stackexchange.com/questions/7850/how-to-edit-parameters-for-an-object-after-it-is-created)

This is also importan to the workflow as it might be needed to edit 3 different lens properties at the same time?

Can there be a workaround for this?

As i have said before, i am a complete blender noob so sorry if i am being ignorant. I love the work you have done here and thanks for sharing it.

**Comment by CodeFHD** [comment]
Two suggestions for what you are trying to do here:

1) Use an actual optical design software. While they are mostly expensive, there are free version around, for example "WinLens Basic" from Qioptiq. This basic version is not that feature-rich, but may help you get started or do some simple tricks.

2) In Blender, you can use an alternative render engine (as opposed to the inbuilt Cycles engine). I have always worked with "LuxCoreRender". With it, you can have a laser source and use volumetric scattering to visualise the rays. Reas-time use is more limited, but can work if you know your material setup.
Personally, I didn't have much time yet to try out other options. I know e.g. of Mitsuba.

One gernic limitation you will have with multi-lens systems in Blender is the limitation to 32-bit resolution. Even if the render engine works with 64-bit the geomtery being 32 bit may limit accuracy for complex lenses. This is not an issue with special lens design software.
Also, the implementations for chromatic aberrations (in LuxCore) are not realistic enough for good simulations.

Regarding the possibility to "edit lens properties after adding it", there is already a feature request for it, but I wouldn't expect to have that soon.

**Comment by CodeFHD** [comment]
I have just added an option "Trace Ray Fan to Scene", as per the linked stackexchanged post in the original issue post.
This feature will only trace rays from the final lens surface that do hit an object, other rays will end at the last lens surface.

As mentioned before, the possibility of editing lens properties is already covered by another open issue. Hence I will close this issue here.

![grafik](https://github.com/CodeFHD/OptiCore/assets/48182552/5566ecdd-eb0a-4be8-8fb8-f8d4c95a9060)
