### ISSUE TITLE
about transmitting rays thorough Plane lens

### ISSUE THREAD

**Issue by Skatasi** [CodeFHD/OptiCore#21]
Hi, I appreciate your great add-ons.
But I have an issue with a Plane lens.

When I made a camera model, I added a plane lens mesh and set S1's R as 0. (Most simulators define Plane as 0. ) However, it didn't consider transmitting rays at plane lenses. 
Then, I made it once more and set S1's R as 10000000000 to assume inf, and it worked.
So, I want to share this issue.

**Comment by CodeFHD** [comment]
Hi, correct, this has been a missing feature from the start (not sure why I was too lazy to put that code segment in).

I've recently started working on updates to the ray-tracing code. This will be implemented as part of that.

**Comment by Skatasi** [comment]
Thx👍

**Comment by CodeFHD** [comment]
I just uploaded the related update. Much of the code for the (standard) lens has been updated and the new raytracing backend is included as well. As far as my tests went, everything now works including the plane surfaces.
