### ISSUE TITLE
Can't install it in Blender 2.91

### ISSUE THREAD

**Issue by SF73** [CodeFHD/OptiCore#4]
Hi, 
First of all, according to the videos on youtube, this addon is amazing !!
But I have some trouble installing it.
When I try I have this error
![image](https://user-images.githubusercontent.com/25269226/116829894-e0d66580-aba6-11eb-9ed2-ab8fcca5a7c1.png)
Any idea how to solve it?

Thanks!

**Comment by CodeFHD** [comment]
Hi,
thanks for the feedback from the videos :)

I found a way to reproduce your error:

Could it be that you reinstalled Opticore, with the addon fodler renamed to "OptiCore-1", without reactivating it inside Blender?

The solution in this case would be to open Blender's addon preferences, search for OptiCore and activate it again. You should even see a warning there

![grafik](https://user-images.githubusercontent.com/48182552/116913968-6c550280-ac4a-11eb-8f2d-2ba3540c0567.png)

**Comment by SF73** [comment]
Well, I don't know exactly. I didn't install Opticore previously and in fact my blender setup is quite clean.
I saw that luxcorerender replaced the dot in their name by underscore.
So I did the same thing (from ``OptiCore-1.0`` initially to ``OptiCore-1_0``) and it worked.

Thanks!

**Comment by CodeFHD** [comment]
Oh that sounds like a good point!
I shall think of it then I again declare a "release version"
Thanks for the feedback!
