### ISSUE TITLE
How to recover the 'lens' panel after first time creating of a lens obj?

### ISSUE THREAD

**Issue by chifenggengmengyue** [CodeFHD/OptiCore#7]
May I ask this stupid question as I am new to blender.
When creating a lens, a lens panel shows up, in which we can edit radius of curvature, etc
But when I do some other operation it disapears and never comes back when I re-select the lens obj...
Is there anyway I can recover the lens panel? Thanks!

**Comment by CodeFHD** [comment]
Unfortunately, this panel isn't directly recoverable. It is an initial constructor-setting, you will find this being the same for the other Blender-internal mesh objects, like a simple cube.

Best workaround I can suggest: Set the Blender cursor to the origin of the lens you want to change. Then delete the lens and recreate it there.

I am looking at storing all properties as custom data of the mesh, also for other purposes, though I don't yet know if it will be possible to add a feature to redraw the geometry at any time. There will at least be side effects, e.g. if you have made mixed material assignments.

**Comment by chifenggengmengyue** [comment]
Thanks! I now understand its an initial constructor setting :)
