### ISSUE TITLE
Different Image behavior using blender 2.92

### ISSUE THREAD

**Issue by chifenggengmengyue** [CodeFHD/OptiCore#8]
Hi, sorry to bother again, I followed exactly the YouTube tutorial video ( OptiCore + LuxCore Lens System Tutorial ) to build the lens, but when I press F12 to render the image I got much noise around the center light spot (also the light spot is not as smooth as it was in the video, I uploaded the result image below). 
I am using blender 2.92+luxcore v2.5, Is this a render engine issue? Can you share the version of blender and luxcore you were using for the video? Thanks!

![spot result](https://user-images.githubusercontent.com/6856955/123293276-6ee72080-d546-11eb-9c87-01ab73fadaef.png)

**Comment by CodeFHD** [comment]
The noise around the center are "fireflies", which usually result from glass reflections. Have you set the "Reflection color" of the LuxCore glass material to perfect black? You also might want to adjust the camera toinemapper settings, especially disable auto-brightness. I judge this from the central spot looking overexposed.

For the shape of the spot, I had similar observations with somewhat low settings of "N1" and "N2" in the OptiCore lens settings, though I have no explanation yet. Try to recreate the lenses with setting N1 and N2 to 64 each.

I am not sure which version exactly I used to make the video, probably v2.4 release, or an early stage daily build of 2.5. Certainly it was Blender 2.8x, not 2.9x.

I won't be able to do detailed testing in the next few days, but it would help if you can share a .blend-file that shows this issue for you. (For any bug, be it Blender, LuxCore, or an addon, sharing a .blend-file is always helpful. Ideally, the .blend-file has the simplest scene that replicates the problem.)

**Comment by chifenggengmengyue** [comment]
Appreciate for the detailed respond! I am detaching my blend file (I renamed to tutorial.gif so that github allows me to upload), I followed your video step by step but a few mistakes might exists..
Also I got a mistake in rendder view saying optixdenoise plug in is missing, I am trying to figure out if this is also a reason.
![tutorial](https://user-images.githubusercontent.com/6856955/123352670-66b4d280-d592-11eb-9ede-ee67f574f394.gif)

**Comment by CodeFHD** [comment]
Thanks for posting the updates. I finally got round to looking at the issue, but now I don't have to :D
